name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build des images Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image backend
        run: docker build ./backend

      - name: Build image frontend
        run: docker build ./frontend
